package com.docscan.scanner

/**
 * Tunables for the high-precision Edge Detection pipeline.
 */
data class EdgeDetectionConfig(
    val processingLongSide: Int,
    val cannyLowFactor: Double,
    val cannyHighFactor: Double,
    val cannyLowBias: Double,
    val claheClipLimit: Double,
    val claheTileSize: Int,
    val morphCloseSize: Int,
    val morphCloseIterations: Int,
    val morphDilateExtra: Int,
    val useScharr: Boolean,
    val useAdaptiveThreshold: Boolean,
    val useHoughClustering: Boolean,
    val houghRho: Double,
    val houghTheta: Double,
    val houghThreshold: Int,
    val houghMinLineLength: Int,
    val houghMaxLineGap: Int,
    val minAreaRatio: Double,
    val maxAreaRatio: Double,
    val minAspect: Double,
    val maxAspect: Double,
    val angleToleranceDeg: Double,
    val internalContrastBoost: Double,
    val requireConvex: Boolean,
    val requirePerpendicularEdges: Boolean,
    val perpendicularToleranceDeg: Double,
    val weightArea: Double,
    val weightGeometry: Double,
    val weightEdge: Double,
    val weightContour: Double,
    val cornerSearchRadiusPx: Int
) {
    companion object {
        val Default = EdgeDetectionConfig(
            processingLongSide = 720,
            cannyLowFactor = 0.48,
            cannyHighFactor = 1.35,
            cannyLowBias = 10.0,
            claheClipLimit = 3.0,
            claheTileSize = 8,
            morphCloseSize = 5,
            morphCloseIterations = 2,
            morphDilateExtra = 1,
            useScharr = true,
            useAdaptiveThreshold = true,
            useHoughClustering = true,
            houghRho = 1.0,
            houghTheta = Math.PI / 180.0,
            houghThreshold = 55,
            houghMinLineLength = 50,
            houghMaxLineGap = 18,
            minAreaRatio = 0.08,          // lowered from 0.12
            maxAreaRatio = 0.97,
            minAspect = 0.28,
            maxAspect = 3.50,
            angleToleranceDeg = 14.0,
            internalContrastBoost = 1.0,
            requireConvex = true,
            requirePerpendicularEdges = true,
            perpendicularToleranceDeg = 10.0,
            weightArea = 0.18,
            weightGeometry = 0.32,
            weightEdge = 0.28,
            weightContour = 0.12,
            cornerSearchRadiusPx = 3
        )

        val ScreenHeavy = EdgeDetectionConfig(
            processingLongSide = 900,
            cannyLowFactor = 0.40,
            cannyHighFactor = 1.55,
            cannyLowBias = 8.0,
            claheClipLimit = 4.0,
            claheTileSize = 8,
            morphCloseSize = 7,
            morphCloseIterations = 3,
            morphDilateExtra = 2,
            useScharr = true,
            useAdaptiveThreshold = true,
            useHoughClustering = true,
            houghRho = 1.0,
            houghTheta = Math.PI / 180.0,
            houghThreshold = 50,
            houghMinLineLength = 40,
            houghMaxLineGap = 25,
            minAreaRatio = 0.06,
            maxAreaRatio = 0.98,
            minAspect = 0.25,
            maxAspect = 4.0,
            angleToleranceDeg = 18.0,
            internalContrastBoost = 1.6,
            requireConvex = true,
            requirePerpendicularEdges = false,
            perpendicularToleranceDeg = 14.0,
            weightArea = 0.18,
            weightGeometry = 0.25,
            weightEdge = 0.32,
            weightContour = 0.10,
            cornerSearchRadiusPx = 3
        )

        val GlossyPaper = EdgeDetectionConfig(
            processingLongSide = 720,
            cannyLowFactor = 0.55,
            cannyHighFactor = 1.30,
            cannyLowBias = 16.0,
            claheClipLimit = 2.5,
            claheTileSize = 8,
            morphCloseSize = 5,
            morphCloseIterations = 2,
            morphDilateExtra = 1,
            useScharr = false,
            useAdaptiveThreshold = false,
            useHoughClustering = true,
            houghRho = 1.0,
            houghTheta = Math.PI / 180.0,
            houghThreshold = 70,
            houghMinLineLength = 70,
            houghMaxLineGap = 14,
            minAreaRatio = 0.12,
            maxAreaRatio = 0.97,
            minAspect = 0.40,
            maxAspect = 2.80,
            angleToleranceDeg = 8.0,
            internalContrastBoost = 0.7,
            requireConvex = true,
            requirePerpendicularEdges = true,
            perpendicularToleranceDeg = 6.0,
            weightArea = 0.20,
            weightGeometry = 0.35,
            weightEdge = 0.20,
            weightContour = 0.10,
            cornerSearchRadiusPx = 2
        )
    }
}